Update host dependencies in debian.yaml
Added debian-archive-keyring, grub, and genisoimage to dependencies.

diff --git a/.github/workflows/debian.yaml b/.github/workflows/debian.yaml
--- a/.github/workflows/debian.yaml
+++ b/.github/workflows/debian.yaml
@@ -74,7 +74,7 @@ jobs:
       - name: Install host dependencies
         run: |
           sudo apt-get update
-          sudo apt-get install -y live-build xorriso syslinux-utils squashfs-tools curl unzip git gpg
+          sudo apt-get install -y live-build xorriso syslinux-utils squashfs-tools curl unzip git gpg debian-archive-keyring grub genisoimage syslinux
 
       - name: Create setup-live-config.sh
         run: |
@@ -173,6 +173,7 @@ jobs:
 
           # GRUB theme
           git clone https://github.com/catppuccin/grub.git && cd grub
+          mkdir /boot/grub/themes/ || echo "failed to make dir"
           cp -r src/* /boot/grub/themes/
           cd ..
           rm -rf grub
